# Generated by Django 4.0.6 on 2022-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=16)),
                ('repeatPassword', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('registrationNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
