# Generated by Django 4.0.6 on 2022-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_signup_repeatpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('regno', models.CharField(max_length=10)),
                ('complainFor', models.CharField(max_length=122)),
                ('sub', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
