# Generated by Django 4.0.6 on 2022-07-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
