# Generated by Django 4.0.6 on 2022-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Seen'), (2, 'Resolved')], default='Pending', max_length=10),
        ),
    ]
