# Generated by Django 4.0.6 on 2022-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='complain',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
