# Generated by Django 4.0.6 on 2022-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_complain_date_alter_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Seen', 'Seen'), ('Resolved', 'Resolved')], default='Pending', max_length=10),
        ),
    ]
