# Generated by Django 4.0.6 on 2022-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_complain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='hostelBlock',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='hostelGender',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='roomNo',
            field=models.CharField(default='default', max_length=5),
            preserve_default=False,
        ),
    ]
