# Generated by Django 4.0.6 on 2022-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_complain_hostelblock_complain_hostelgender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='hostelBlock',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='hostelGender',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='roomNo',
        ),
        migrations.AddField(
            model_name='complain',
            name='roomDetails',
            field=models.CharField(default='nothingnothing', max_length=100),
            preserve_default=False,
        ),
    ]
