# Generated by Django 4.0.6 on 2022-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_complain_hostelblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
