# Generated by Django 4.0.6 on 2022-08-01 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_complain_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='roomDetails',
            new_name='hostelBlock',
        ),
        migrations.AddField(
            model_name='complain',
            name='complainResolveDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='complain',
            name='hostelBlockDepartmentSupervisor',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AddField(
            model_name='complain',
            name='hostelBlockSupervisor',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AddField(
            model_name='complain',
            name='hostelName',
            field=models.CharField(default='Block 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='roomNumber',
            field=models.CharField(default='653A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='workerName',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
