# Generated by Django 4.0.6 on 2022-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_complain_complainresolvedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complainResolveDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
